#######################################################
# 
# PictureProcessing.py
# Python implementation of the Class PictureProcessing
# Generated by Enterprise Architect
# Created on:      26-okt-2021 09:58:08
# Original author: orjan
# 
#######################################################

from csdt_stl_tools import numpy2stl
from scipy.ndimage import gaussian_filter
from cv2 import cv2


class PictureProcessing:

    def __init__(self):
        pass

    def segment_image(self, image):
        self.image = cv2.imread(f'{image}', 0)
        A = self.image
        A = gaussian_filter(self.image, 1)  # smoothing
        numpy2stl(A, 'icon.stl', scale=0.1, solid=True, ascii=False,)

    def set_image(self):
        pass
