#######################################################
# 
# STLGenerator.py
# Python implementation of the Class STLGenerator
# Generated by Enterprise Architect
# Created on:      26-okt-2021 09:58:08
# Original author: orjan
# 
#######################################################

import numpy2stl as stl
from scipy.ndimage import gaussian_filter
from cv2 import cv2


class STLGenerator:

    def __init__(self):
        pass

    def generate_stl(self, image):
        print('Generating stl-file...')
        print('Please wait...')
        self.image = cv2.imread(f'{image}', 0)
        A = self.image
        A = gaussian_filter(self.image, 1)  # smoothing
        stl.numpy2stl(A, 'icon.stl', scale=0.05, solid=True, ascii=False)
        print('Done, check your library.')
        print('Goodbye!')