#######################################################
# 
# Weather.py
# Python implementation of the Class Weather
# Generated by Enterprise Architect
# Created on:      26-okt-2021 09:58:08
# Original author: orjan
# 
#######################################################


class Weather:
    def check_location() -> bool:
        pass

    def get_weather(_location):
        pass

    def set_location(_location):
        pass